name: 
author: 
url: MINJE-98.github.io
baseurl: MINJE-98.github.io
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
