# User config
author: "MINJE-98.github.io"
tagline: ""
description: "Anyone can do it"
keywords: "TypeScript, BlockChain"
email: "minje9801@gmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
github: https://github.com/MINJE-98

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
