# User config
author: "_minje"
tagline: "Pineapple Certfied Jekyll Theme"
description: "시작이 반이다..."
keywords: "TypeScript, BlockChain"
email: "minje9801@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: https://github.com/MINJE-98

# Site config
baseurl: "https://minje-98.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
